name: Android CI
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: android-actions/setup-android@v3
      - run: sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew :app:assembleDebug
      - uses: actions/upload-artifact@v4
        with: { name: BrightnessPulse-debug, path: app/build/outputs/apk/debug/*.apk }
